name: CI

on:
  push:
    branches:
      - 'main'
      - 'test-feature-BL-15047-doctrine-cache'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - run: sudo composer self-update 2.2.24

  static:
    needs: setup
    uses: dvsa/.github/.github/workflows/php-library-static.yml@v4.0.1

  test:
    needs: setup
    uses: dvsa/.github/.github/workflows/php-library-tests.yml@v3.2.3
    with:
      php-versions: "[\"8.2\"]"

  security:
    needs: setup
    uses: dvsa/.github/.github/workflows/php-library-security.yml@v3.2.3
    with:
      php-versions: "[\"8.2\"]"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
